#!/bin/sh /etc/rc.common
#
# Copyright (C) 2009 OpenWrt.org
#

START=70
STOP=12

USE_PROCD=1
NAME=dectmngr2
PROG=/usr/sbin/dectmngr-wrapper.sh



start_service() {
	# Kernel Dect module is very sensitive for
	# long periods of disabled interrupts.
	echo 1 >/proc/sys/kernel/printk_with_interrupt_enabled

	# Create default Dect data storage if missing. The
	# dectmngr2 will read RFPI from /proc/nvram.
	if [ ! -s /etc/dect/nvs -a -s /etc/dect/nvs_default ]; then
		cp /etc/dect/nvs_default /etc/dect/nvs

		DECTANTDIV=`db get hw.board.DectAntennaDiversity`
		case "$DECTANTDIV" in
			1|off) echo -ne "\x01" > /tmp/dect_antenna_diversity ;;
			2) echo -ne "\x02" > /tmp/dect_antenna_diversity ;;
			*) echo -ne "\x00" > /tmp/dect_antenna_diversity ;;
		esac

		dd of=/etc/dect/nvs if=/tmp/dect_antenna_diversity conv=notrunc bs=1 seek=32
		fsync /etc/dect/nvs
	fi

	procd_open_instance
	procd_set_param command $PROG --app
	procd_set_param respawn "5" "0" "0"
	procd_close_instance
}

stop_service() {
	if [ "$(cat /tmp/defaultreset 2>/dev/null)" == "1" ]; then
		local _i=1
		json_load "$(ubus -t 5 call dect handset "{'list':''}")"
		json_select handsets
		while json_get_var hs $_i; do
			json_select $_i
			json_get_var id id;
			ubus -t 5 call dect handset "{'delete':$_i}" 2>/dev/null
			json_select ..
			_i=$((_i+1))
		done
		sleep 1
	fi
	killall -q $NAME
}

reload_service() {
	killall -q $NAME
	start
}

service_triggers()
{
	procd_add_reload_trigger dect
}

boot() {
	start
}
