#!/bin/sh /etc/rc.common
#
# Copyright (C) 2009 OpenWrt.org
#

START=70
STOP=12

USE_PROCD=1
NAME=dectmngr2
PROG=/usr/sbin/dectmngr2



start_service() {
	# Kernel Dect module is very sensitive for
	# long periods of disabled interrupts.
	echo 1 >/proc/sys/kernel/printk_with_interrupt_enabled

	# Create default Dect data storage if missing. The
	# dectmngr2 will read RFPI from /proc/nvram.
	if [ ! -s /etc/dect/nvs -a -s /etc/dect/nvs_default ]; then
		cp /etc/dect/nvs_default /etc/dect/nvs

		DECTANTDIV=`db get hw.board.DectAntennaDiversity`
		case "$DECTANTDIV" in
			1|off) echo -ne "\x01" > /tmp/dect_antenna_diversity ;;
			2) echo -ne "\x02" > /tmp/dect_antenna_diversity ;;
			*) echo -ne "\x00" > /tmp/dect_antenna_diversity ;;
		esac

		dd of=/etc/dect/nvs if=/tmp/dect_antenna_diversity conv=notrunc bs=1 seek=32
		fsync /etc/dect/nvs
	fi

	procd_open_instance
	procd_set_param command "$PROG" --app
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	killall -q $NAME
	sleep 1
	grep -q dect /proc/modules && rmmod dect
	[ -s /lib/modules/*/extra/dect.ko ] && insmod /lib/modules/*/extra/dect.ko
}

reload_service() {
	stop
	start
}

service_triggers()
{
	procd_add_reload_trigger dect
}

boot() {
	start
}
